server:
  port: 7240
  error:
    include-message: always
build:
  version: @project.version@

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    # show-sql: true
    properties:
      hibernate:
        default_schema: tracker
        types.print.banner: false
  datasource:
    url: jdbc:postgresql://localhost:5433/tracker
    username: tracker
    password: tracker
  flyway:
    enabled: true
    baseline-on-migrate: true
    encoding: utf8
    default-schema: tracker
    schemas:
      - tracker
    locations: classpath:db/migrations
  batch:
    job:
      enabled: false
security:
  jwt:
    secret: cmVuZGljaW9uZXNzZWNyZXRvc2VjcmV0b3JlbmRpY2lvbmVzMTIzNDU2Nzg5
    expiration: 3153600
mqtt:
  url: tcp://nam1.cloud.thethings.network
  user-name: poc-arauco@ttn
  pass: NNSXS.MAJEWVYJWIMVR765UP2Y5UR64FCCFMSSWYJAXPY.UUNMIGF3W5WQLNMA5MJR6O3R2SYC6N2E4BQUWVGLYJ4PMSYZB4CQ
  topics:
    root: v3/poc-arauco@ttn
    tracking: devices/lbt1-arauco/up

